language: python
python:
  - "3.6"
cache: pip
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
# command to configure build notifications
notifications:
  email: false
  # command to integrate travis with gitter notifications
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d627377180466a7d65b8
    on_success: change #options: [always|never|change] default: always
    on_failure: always
    on_start: never
# command to configure travis for recent git builds
git:
  depth: 3
# command to configure services
services: mongodb

